const product_card = [
  {
    id: 1,
    product_name: "Beef Top Sirloin Steak",
    description: "Includes 1 piece of steak",
    price: 10,
    currency: "$",
    thumb: "./images/1.png",
  },
  {
    id: 2,
    product_name: "Fresh Salmon",
    description: "Fresh Fish",
    price: 20,
    currency: "$",
    thumb: "./images/2.png",
  },
  {
    id: 3,
    product_name: "Pasture Raised Eggs",
    description: "Total of 10 Eggs",
    price: 6,
    currency: "$",
    thumb: "./images/3.png",
  },
  {
    id: 4,
    product_name: "Chicken",
    description: "Boneless Chicken Thighs",
    price: 8,
    currency: "$",
    thumb: "./images/4.png",
  },
  {
    id: 5,
    product_name: "Chicken and Vegetable Stir Fry",
    description: "Keto Meal",
    price: 4,
    currency: "$",
    thumb: "./images/5.png",
  },
  {
    id: 6,
    product_name: "Whole Wheat Bread",
    description: "100% Whole Wheat",
    price: 3,
    currency: "$",
    thumb: "./images/6.png",
  },
  {
    id: 7,
    product_name: "Low Fat Milk",
    description: "Reduced Fat, 1% Milk",
    price: 2,
    currency: "$",
    thumb: "./images/7.png",
  },
  {
    id: 8,
    product_name: "Bananas",
    description: "Organic Bananas",
    price: 2,
    currency: "$",
    thumb: "./images/8.png",
  },
  {
    id: 9,
    product_name: "Apples",
    description: "Organic Apples - 3 lb",
    price: 4,
    currency: "$",
    thumb: "./images/9.png",
  },
];
export default product_card;
